name: workflow_dispatch- SST APP 
permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write

on:
  # push:
  pull_request:
    types: [closed, merged, labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  call-workflow-preview:
    uses: VishwajitNagulkar/sst-test2/.github/workflows/sstcalled2.yml@master
    with:
      app-env: preview                  
      working-directory: './floaws/my-sst-app'      ## specify your working folder from repo
    secrets:
      ACCOUNT: ${{ secrets.ACCOUNT_PROD }}

  call-workflow-stage:
    if: ${{ github.base_ref == 'stage' }}
    uses: clouddrove-sandbox/test-environment-sst-2/.github/workflows/sst_called_test28.yml@master
    with:
      app-env: stage                      
      working-directory: './floaws/my-sst-app'      ## specify your working folder from repo
    secrets:
      ACCOUNT: ${{ secrets.ACCOUNT_PROD }}

  call-workflow-prod:
    if: ${{ github.base_ref == 'master' }}
    uses: clouddrove-sandbox/test-environment-sst-2/.github/workflows/sst_called_test28.yml@master
    with:
      app-env: prod
      working-directory: './floaws/my-sst-app'      ## specify your working folder from repo
    secrets:
      ACCOUNT: ${{ secrets.ACCOUNT_PROD }}
